"""empty message

Revision ID: 4992d711157a
Revises: 9e0b43a34e07
Create Date: 2024-03-22 06:56:02.720140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4992d711157a'
down_revision = '9e0b43a34e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rehaan', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('rehaan')

    # ### end Alembic commands ###
