# import the necessary components first
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import ssl

port = 587
smtp_server = "live.smtp.mailtrap.io"
login = "crlsclubfinder@gmail.com" # paste your login generated by Mailtrap
password = "wmzhhaxtzqnvyuze" # paste your password generated by Mailtrap

# email_sender = "crlsclubfinder@gmail.com"
# email_password = "wmzhhaxtzqnvyuze"
# email_receiver = email
# subject = "Change ClubFinder Pasword"

sender_email = "crlsclubfinder@gmail.com"
receiver_email = "rehaan1099@gmail.com"
message = MIMEMultipart("alternative")
message["Subject"] = "multipart test"
message["From"] = sender_email
message["To"] = receiver_email

# write the text/plain part
text = """\
Hi,
Check out the new post on the Mailtrap blog:
SMTP Server for Testing: Cloud-based or Local?
https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
Feel free to let us know what content would be useful for you!"""

# write the HTML part
html = """\
<html>
  <body>
    <p>Hi,<br>
      Check out the new post on the Mailtrap blog:</p>
    <p><a href="https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server">SMTP Server for Testing: Cloud-based or Local?</a></p>
    <p> Feel free to <strong>let us</strong> know what content would be useful for you!</p>
  </body>
</html>
"""

# convert both parts to MIMEText objects and add them to the MIMEMultipart message
part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")
message.attach(part1)
message.attach(part2)

# send your email
# with smtplib.SMTP("live.smtp.mailtrap.io", 587) as server:
#     server.login(login, password)
#     server.sendmail(
#         sender_email, receiver_email, message.as_string()
#     )

context = ssl.create_default_context()

with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
        smtp.login(sender_email, password)
        smtp.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')